#!/bin/bash
# Arguments - URL
URL2=$(echo $1 | cut -d \/ -f 1-3)$(curl -L $1 | grep m3u | cut -d \" -f 2)
FILELIST=$(wget -qO- $URL2) 
DLDIR=$(echo $FILELIST | cut -d \/ -f 5)
mkdir -p $DLDIR && echo $FILELIST | xargs -n 1 -P 10 wget -P $DLDIR -c 
